#!/bin/bash

## PARAMETER HELP FUNCTION
helpFunction()
{
   echo ""
   echo "Usage: $0 -w1 Worker 1 hostname -w2 Worker 2 hostname -i Ingress port -e Egress port"
   echo -e "\t-w1 Worker 1 hostname"
   echo -e "\t-w2 Worker 1 hostname"
   echo -e "\t-i Ingress port"
   echo -e "\t-e Egress port"
   exit 1 # Exit script after printing help
}

while getopts "s:p:" opt
do
   case "$opt" in
      w1 ) export worker1="$OPTARG" ;;
      w2 ) export worker2="$OPTARG" ;;
      i ) export ingress="$OPTARG" ;;
      e ) export egress="$OPTARG" ;;
      ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent
   esac
done

### Print helpFunction in case parameters are empty
if [ -z "$worker1" ] || [ -z "$worker2" ] || [ -z "$ingress" ] || [ -z "$egress" ]
then
   echo "WARNING: Some or all of the parameters are empty";
   helpFunction
fi

### Begin script in case all parameters are correct
echo ""
echo "*** READY TO START INSTALLATION ***"
echo ""
echo "- Worker 1 hostnme is $worker1"
echo "- Worker 2 hostnme is $worker2"
echo "- Ingress port is $ingress"
echo "- Egress port is $egress"
echo ""

echo ""
echo "*** LABELLING WORKER NODES... ***"
echo ""

kubectl label nodes $worker1 node-role.kubernetes.io/worker=true
kubectl label nodes $worker2 node-role.kubernetes.io/worker=true

echo ""
echo "*** INSTALLING NMSTATE... ***"
echo ""

kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.74.0/nmstate.io_nmstates.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.74.0/namespace.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.74.0/service_account.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.74.0/role.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.74.0/role_binding.yaml
kubectl apply -f https://github.com/nmstate/kubernetes-nmstate/releases/download/v0.74.0/operator.yaml

cat <<EOF | kubectl create -f -
apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: nmstate
EOF

echo ""
echo "*** CREATING LINUX BRIDGES FOR INGRESS... ***"
echo ""

cat <<EOF | kubectl apply -f -
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ingress
spec:
  nodeSelector: 
    node-role.kubernetes.io/worker: "true"
  desiredState:
    interfaces:
    - name: ingress
      description: Linux bridge tied to $ingress
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: $ingress
EOF

echo ""
echo "*** VERIFYING INGRESS BRIDGE... ***"
echo ""

kubectl wait nncp ingress --for condition=Available --timeout 2m

echo ""
echo "*** CREATING LINUX BRIDGES FOR INGRESS... ***"
echo ""

cat <<EOF | kubectl apply -f -
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: egress
spec:
  nodeSelector: 
    node-role.kubernetes.io/worker: "true"
  desiredState:
    interfaces:
    - name: egress
      description: Linux bridge tied to $egress
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: $egress
EOF

echo ""
echo "*** VERIFYING EGRESS BRIDGE... ***"
echo ""

kubectl wait nncp egress --for condition=Available --timeout 2m
